name: Test & Build

on:
  workflow_call:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ 1.19 ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        # skip cache because of flaky behaviors
        skip-build-cache: true
        skip-pkg-cache: true
    - run: make test
